# Generated by Django 5.1.4 on 2025-05-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Coming', 'Coming'), ('New Listed', 'New Listed')], default='Ongoing', max_length=20),
        ),
    ]
